_target_:  pytorch_lightning.Trainer
max_epochs: 1000
accelerator: gpu
devices: [0]
deterministic: False
detect_anomaly: False
enable_progress_bar: True
strategy: ddp # ddp_find_unused_parameters_true
precision: 32

# accumulate_grad_batches:
val_check_interval: 300
log_every_n_steps: 1
num_sanity_val_steps: 2
limit_val_batches: 
limit_test_batches:

# Define callbacks
defaults:
  - logger: tensorboard

callbacks: "${oc.dict.values: callback}"
